# Website's icon url.
favicon: /favicon.ico

# Open Graph metadata (https://hexo.io/docs/helpers.html#open-graph)
open_graph:
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:

# Website's logo shown on the left of the navigation bar.
# It can either be an url to an image or a string if the following option is set.
# logo:
#   text: <logo string>
logo: /assets/about/avatar.jpg

article:
  # Show word count and estimated reading time.
  readtime: false

# Navigation bar menu links.
menu:
  主页: /
  归档: /archives
  分类: /categories
  标签: /tags
  技巧: /cheat-sheet
  # 当前赛季比赛列表: /regional-contests

# Search plugin settings.
search:
  type: insight

# Navigation bar toc settings
toc: true

# Share plugin settings.
# share:
#   type: sharethis
#   install_url:

# Comment plugin settings.
comment:
  type: gitalk
  owner: ChieloNewctle
  repo: chielonewctle.github.io
  admin:
  - ChieloNewctle
  client_id: f14a9588509f70e5daf3
  client_secret: b91f31763cfd5e1da04f45f23717b7564638c1fd

# Other plugins and their settings.
plugins:
  mathjax: true
  katex: false
  gallery: true
  clipboard: true
  google-analytics:
    tracking_id:

# Additional navigation bar links on the right.
# Links can either be text or icon. The following link is set to be an icon link whose icon
# is set to the class name of a FontAwesome 5 icon. The `footer_links` below also gives an
# example of setting plain text links.
navbar_links:
  # Email:
  #   icon: fas fa-envelope
  #   url: mailto:chielonewctle@yandex.com

# Links at the bottom of the page.
footer_links:
  RSS: /atom.xml
  Email: mailto:chielonewctle@yandex.com
  Theme: https://github.com/ChieloNewctle/hexo-theme-minos
